return {
  -- { "folke/noice.nvim", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  { "folke/flash.nvim", enabled = false },
  -- { "nvim-telescope/telescope.nvim", enabled = false },
  -- { "nvim-telescope/telescope-fzf-native.nvim", enabled = false },
  { "nvim-treesitter/nvim-treesitter-textobjects", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "echasnovski/mini.surround", enabled = false },
  { "neo-tree.nvim", enabled = false },
  -- { "nvimdev/dashboard-nvim", enabled = false },
  -- { "mini.pairs", enabled = false },
  -- { "indent-blankline.nvim", enabled = false },
  -- { "mini.indentscope", enabled = false },
}
